version: '3.8'

services:
  # Main Data Analyzer Application (without Ollama dependency)
  dataanalyzer:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./excel_files:/app/excel_files
      - ./databases:/app/databases
      - ./ducklake:/app/ducklake
      - ./generated_code:/app/generated_code
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-ollama}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-http://host.docker.internal:11434/v1}
      - LLM_MODEL=${LLM_MODEL:-qwen2.5:latest}
      - CODING_MODEL=${CODING_MODEL:-qwen2.5-coder:latest}
      # Database connections to local instances
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING:-mongodb://dataanalyzer:dataanalyzer_pwd@host.docker.internal:27017/my_test_db?authSource=test}
      - MARIADB_CONNECTION_STRING=${MARIADB_CONNECTION_STRING:-mariadb+mariadbconnector://dataanalyzer:dataanalyzer_pwd@host.docker.internal:3306/my_test_db}
    networks:
      - dataanalyzer-network
    restart: unless-stopped

  
  # Jupyter Notebook for additional data science workflows (optional)
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./databases:/home/jovyan/databases
      - ./ducklake:/home/jovyan/ducklake
      - ./excel_files:/home/jovyan/excel_files
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=dataanalyzer123
    networks:
      - dataanalyzer-network
    restart: unless-stopped
    profiles:
      - jupyter

  # Metabase for BI dashboards (optional)
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    networks:
      - dataanalyzer-network
    restart: unless-stopped
    profiles:
      - metabase

volumes:
  metabase_data:

networks:
  dataanalyzer-network:
    driver: bridge
