version: '3.8'

services:
  # Main Data Analyzer Application
  dataanalyzer:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./excel_files:/app/excel_files
      - ./databases:/app/databases
      - ./ducklake:/app/ducklake
      - ./generated_code:/app/generated_code
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-ollama}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-http://ollama:11434/v1}
      - LLM_MODEL=${LLM_MODEL:-qwen2.5:latest}
      - CODING_MODEL=${CODING_MODEL:-qwen2.5-coder:latest}
    depends_on:
      - ollama
    networks:
      - dataanalyzer-network
    restart: unless-stopped

  # Ollama for local LLM support
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - dataanalyzer-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # MongoDB for additional database support (optional)
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=dataanalyzer
    networks:
      - dataanalyzer-network
    restart: unless-stopped

  # MariaDB for additional database support (optional)
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dataanalyzer
      - MYSQL_USER=dataanalyzer
      - MYSQL_PASSWORD=dataanalyzer_pwd
    networks:
      - dataanalyzer-network
    restart: unless-stopped

  # Jupyter Notebook for additional data science workflows (optional)
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./databases:/home/jovyan/databases
      - ./ducklake:/home/jovyan/ducklake
      - ./excel_files:/home/jovyan/excel_files
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=dataanalyzer123
    networks:
      - dataanalyzer-network
    restart: unless-stopped

  # Metabase for BI dashboards (optional)
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    networks:
      - dataanalyzer-network
    restart: unless-stopped

volumes:
  ollama_data:
  mongodb_data:
  mariadb_data:
  metabase_data:

networks:
  dataanalyzer-network:
    driver: bridge
